# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(max_length=20, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(max_length=20, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(max_length=20, upload_to='image'),
        ),
    ]
